### ISSUE TITLE
Updating EDD core with Auto Register active generates error

### ISSUE THREAD

**Issue by kerijacoby** [easydigitaldownloads/edd-auto-register#68]
### Expected behavior
When EDD core is updated with Auto Register activated the plugin should update without errors or warning.

### Actual behavior
When updating the following error is displayed:
![Screen Shot 2019-10-03 at 5 30 44 AM](https://user-images.githubusercontent.com/30249621/66240773-3d1f8d80-e6c3-11e9-920d-f2984bac199f.png)

### Steps to reproduce the behavior
Needs replication. I updated from Version 2.9.16 of EDD to Version 2.9.17 with Auto Register active and was not able to replicate. 

### Information:
PHP Version: Version 7.0.3

EDD Auto Register Version (or branch): Version 1.3.10

EDD Version (or branch): Version 2.9.16 to Version 2.9.17

WordPress Version: Version 5.2.3

Any other relevant information: NA

**Comment by pippinsplugins** [comment]
This happens when the debug file isn't writable on the server. EDD core handles this gracefully but Auto Register doesn't.

We adding error logging for Auto Register before debug logging was added to EDD core (if my memory serves). Core has had debug logging for long enough now, however, that I feel we can remove the problematic error logging here entirely.
